name: Test and Deploy API

on:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: "Deploy to production?"
        required: true
        default: "no"
        type: choice
        options:
          - "no"
          - "yes"
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-api.yml"

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and start TigerBeetle
        run: |
          curl -Lo tigerbeetle.zip https://linux.tigerbeetle.com && unzip tigerbeetle.zip
          ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 --development ./0_0.tigerbeetle
          ./tigerbeetle start --addresses=4000 --development  ./0_0.tigerbeetle &
          
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: backend/RetailBankTest
        run: dotnet restore

      - name: Run unit and integration tests
        working-directory: backend/RetailBankTest
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/RetailBankTest/TestResults
      
  deploy:
    needs: [test]
    if: ${{ github.event.inputs.deploy_prod == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Get EC2 public IP from the repo variable
        id: tf_output
        run: |
          echo "EC2_HOST=${{ vars.EC2_HOST }}" >> $GITHUB_ENV

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 
      
      - name: Stop systemd service if its already running
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_HOST << 'EOF'
          [ -f "/etc/systemd/system/retail-bank.service" ] && sudo systemctl stop retail-bank.service || true # ignore non-zero error code
          

      - name: Build the api and move copy to the ec2
        working-directory: backend/RetailBank
        run: |
            dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true
            scp -o StrictHostKeyChecking=no -i ../../ec2_key.pem ./bin/Release/net8.0/linux-x64/publish/* ubuntu@$EC2_HOST:~/build 
      
      - name: Copy app settings.json over
        working-directory: backend/RetailBank
        run: |
          scp -r -o StrictHostKeyChecking=no -i ../../ec2_key.pem appsettings.json ubuntu@$EC2_HOST:~/build

      - name: Setup Node.js for frontend build
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build 
      - name: Copy frontend build result to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no -i ec2_key.pem ./frontend/dist/* ubuntu@$EC2_HOST:~/frontend-build
       
      - name: Copy start.sh over
        run: |
          scp -r -o StrictHostKeyChecking=no -i ec2_key.pem start.sh ubuntu@$EC2_HOST:~/start.sh

      - name: Copy tigerbeetle setup over
        run: |
          scp -r -o StrictHostKeyChecking=no -i ec2_key.pem ./backend/setup-tigerbeetle.sh ubuntu@$EC2_HOST:~/setup-tigerbeetle.sh
      
      - name: Run start script
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_HOST << 'EOF'
          sudo bash ~/start.sh

      
