name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy
        run: |
          scp -i key.pem -r ./frontend/* ${{ vars.EC2_HOST }}:/home/ubuntu/frontend/

          ssh -o StrictHostKeyChecking=no -i key.pem ${{ vars.EC2_HOST }} << 'EOF'
          EOF
