name: Deploy API

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-api.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy
        run: |
          # Copy backend to EC2
          scp -i key.pem -r ./backend/* ubuntu@${{ vars.EC2_HOST }}:~/api

          # Build and run on EC2
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ vars.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/api/RetailBank
            
            # Kill any existing process
            pkill -f "dotnet.*RetailBank" || true
            
            # Build and run
            dotnet restore
            dotnet build --configuration Release
            nohup dotnet run --configuration Release --urls "http://0.0.0.0:5000" > /home/ubuntu/api.log 2>&1 &
            
            echo "API deployed and running on port 5000"
          EOF
